// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// decision_bfb_cpp
bool decision_bfb_cpp(IntegerVector counts_r);
RcppExport SEXP _bfbtools_decision_bfb_cpp(SEXP counts_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type counts_r(counts_rSEXP);
    rcpp_result_gen = Rcpp::wrap(decision_bfb_cpp(counts_r));
    return rcpp_result_gen;
END_RCPP
}
// nearest_bfb_weighted_cpp
List nearest_bfb_weighted_cpp(IntegerVector counts_r, int model, double minLogWeight, int maxFrontier);
RcppExport SEXP _bfbtools_nearest_bfb_weighted_cpp(SEXP counts_rSEXP, SEXP modelSEXP, SEXP minLogWeightSEXP, SEXP maxFrontierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type counts_r(counts_rSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    Rcpp::traits::input_parameter< double >::type minLogWeight(minLogWeightSEXP);
    Rcpp::traits::input_parameter< int >::type maxFrontier(maxFrontierSEXP);
    rcpp_result_gen = Rcpp::wrap(nearest_bfb_weighted_cpp(counts_r, model, minLogWeight, maxFrontier));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bfbtools_decision_bfb_cpp", (DL_FUNC) &_bfbtools_decision_bfb_cpp, 1},
    {"_bfbtools_nearest_bfb_weighted_cpp", (DL_FUNC) &_bfbtools_nearest_bfb_weighted_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bfbtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
