# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Linear-time BFB count-vector decision
#'
#' Direct port of the linear-time algorithm of Zakov, Kinsella & Bafna
#' (PNAS 2013) for deciding whether a count-vector admits a BFB
#' schedule. Unlike bfbtools::bfb_tree()/admits_bfb_schedule() (which
#' implement the earlier, worst-case-exponential algorithms of
#' Kinsella & Bafna 2012), this algorithm is provably O(N) time, with
#' no backtracking or search budget ever needed.
#'
#' Note on array order: the reference Java implementation's internal
#' `counts[l]` array is processed centromere-to-telomere (it folds
#' counts[k-1] first, counts[0] last), the reverse of the
#' telomere-to-centromere convention used throughout bfbtools and in
#' Kinsella & Bafna (2012). This function reverses the input before
#' calling the ported algorithm, so callers can pass count-vectors in
#' the same (telomere-to-centromere) order used everywhere else.
#'
#' @param counts_r integer count-vector (all entries >= 1), telomere
#'   to centromere.
#' @return TRUE if the count-vector admits a BFB schedule, FALSE
#'   otherwise.
decision_bfb_cpp <- function(counts_r) {
    .Call(`_bfbtools_decision_bfb_cpp`, counts_r)
}

nearest_bfb_weighted_cpp <- function(counts_r, model, minLogWeight, maxFrontier) {
    .Call(`_bfbtools_nearest_bfb_weighted_cpp`, counts_r, model, minLogWeight, maxFrontier)
}

